#!/bin/bash

echo 'Sadly, there are still a few things on your list!'
echo 'Install these apps from their respective sources:'
echo 'Adobe creative suite: acrobat, audition, photoshop'
echo 'VS code'
echo 'Hey'
echo 'Ecamm Call Recorder'
echo 'Elgato Control Center'
echo 'Stream Deck'
echo 'Restream Chat'
echo 'Deckset'
echo 'open 1pasword and log in'
echo 'open choosy and let it take over and customize the list'
echo 'Open BusyCal and authenticate with iCloud and google'
