#!/usr/bin/env bash

# Install additional composer dependencies as you would from the command line.
#echo "
#Installing Tailwind preset
#"

#composer require laravel-frontend-presets/tailwindcss --dev
#php artisan ui tailwindcss --auth
#npm install && npm run dev
#git add .
#git commit -am "Add Tailwind and Auth"

# To copy standard files to new lambo project place them in ~/.lambo/includes directory.
echo "
Copying Include Files to $PROJECTPATH
"
cp -R ~/.lambo/includes/ $PROJECTPATH

# To add a git commit after given modifications
echo "
Committing after modifications to Git
"
git add .
git commit -am "Add include files."

