#!/usr/bin/env bash

PROJECTPATH="."
MESSAGE="Initial commit."
DEVELOP=false
CODEEDITOR="code"
BROWSER=""
LINK=false

# Run the standard Laravel database migrations.
# options:
#   true, 1, "yes" or "on"
#   false (default), 0, "no" or "off"
MIGRATE_DATABASE=false

# The database host. Defaults to 127.0.0.1.
#DB_HOST=127.0.0.1

# The database port. Defaults to 3306.
#DB_PORT=

# The database name. Defaults to the project name.
#DB_NAME=
