# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="dstufft"

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
ZSH_DISABLE_COMPFIX=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting vi-mode z laravel)

source $ZSH/oh-my-zsh.sh

# Fun custom config
bindkey "[D" backward-word
bindkey "[C" forward-word

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

source ~/dotfiles/files/aliases
source ~/dotfiles/files/functions

if [[ -f ~/.dotfiles/extra ]]; then
    source ~/.dotfiles/extra
fi

# GitHub instead of Git
# eval "$(hub alias -s)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# --- PATH ------------------------------------
export PATH="/usr/local/sbin:$PATH" # Necessary for PHP FPM from homebrew to be prioritized correctly
export PATH="./vendor/bin:$PATH" # Composer vendor directory
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin" # Postgres tools
export PATH="$PATH:$HOME/.composer/vendor/bin" # Global Composer vendor directory
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
